name = "file-share-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "file-share"

[[d1_databases]]
binding = "DB"
database_name = "file-share"
database_id = "1cdfa96b-734c-4ec2-ae66-3cd304dff3b4"    # Will be set during deployment
